### ISSUE TITLE
Slashes in JSON property names cannot be escaped

### ISSUE THREAD

**Issue by stewx** [magic-chunks/magic-chunks-dotnetcore#59]
We need to transform a JSON file that looks like this:

```
{
 "dependencies": {
    "acme/mypackage": "1.0.0"  
  }
}
```

I want to change "1.0.0" to something else, say, "2.0.0".

Doing the following:
`{ "dependencies/acme/mypackage": "2.0.0"}`

Produces the following output:
```
{
 "dependencies": {
    "acme/mypackage": "1.0.0",
    "acme": {
      "mypackage": "2.0.0"
    }
  }
}
```

I would like to do the following:
`{ "dependencies/acme\/mypackage": "2.0.0"}`

But it produces:
```
{
 "dependencies": {
    "acme/mypackage": "1.0.0",
    "acme\\": {
      "mypackage": "2.0.0"
    }
  }
}
```

**Comment by Sigman32** [comment]
this issue is similar to #54
