### ISSUE TITLE
Config Transformation not available from VSTS Release Definition

### ISSUE THREAD

**Issue by ghelyar** [magic-chunks/magic-chunks-dotnetcore#74]
I have installed the Magic Chunks extension into VSTS and can see Config Transformation when editing a Build Definition, but can't see it when editing a Release Definition, which is when I actually want to be setting the configuration so that it can be different for different releases.

Is this possible, or does it have to be done with PowerShell for a release definition?

**Comment by MisinformedDNA** [comment]
I'm using it in my Release Definition. Maybe it was fixed?
